---
- hosts: all

  vars:
    new_db_user: test_user
    new_db_pass: password

  roles:
    - bbatsche.PostgreSQL-Install

  pre_tasks:
    - name: Get ENV
      set_fact: raw_value={{ lookup('env', 'DB_NAME') }}

    - name: Set DB Name Version
      set_fact: db_name={{ raw_value }}
      when: raw_value != ''

  tasks:
    - include: tasks/main.yml
