---
- name: Create User
  postgresql_user:
    name:           "{{ new_postgres_user }}"
    password:       "{{ new_postgres_pass }}"
    db:             postgres
    encrypted:      yes
    login_user:     "{{ postgres_admin }}"
    login_password: "{{ postgres_pass }}"
    state:          present
    role_attr_flags: "{{ 'SUPERUSER,CREATEDB,CREATEROLE,REPLICATION' if db_name|default('') == '' else '' }}"

- include: database.yml
  when: db_name | default('') != ''
